#!/usr/bin/env python3

import pandas as pd
import matplotlib.pyplot as plt

column_names = ['STOCK #', 'VIN', 'YEAR', 'MAKE',
    'MODEL', 'MILEAGE (IN KM)', 'CERTIFIED PRE-OWNED (Y/N)',
    'PHOTO COUNT', 'COLOR', 'INTERIOR',
    'LIST PRICE', 'DISCOUNT', 'REBATE', 'SELLING PRICE',
    'FINANCE PRICE', 'FINANCE TERM (IN MONTHS)', 'DATE']

# defining dataframe as df from cars.csv, using column names
df = pd.read_csv('cars.csv', names = column_names)

# just exploring the data here
print(df.head(10)) # printing the first 10
print(df.tail(20)) # printing the last 20
print(df.sample(n=10)) # random sample of 10

# setting the two columns in the dataframe
mileage = df["MILEAGE (IN KM)"] 
list_price = df["LIST PRICE"]

# creating scatter plot
plt.scatter(mileage, list_price, c='teal', alpha=0.6, marker='o', edgecolors='white')
plt.xlabel("Mileage, in km", fontsize=14)
plt.ylabel("List Price", fontsize=14)
plt.title("Odometer vs Price", fontsize=16)
plt.grid(True, linestyle='--', linewidth=0.5, alpha=0.7)

# adding a color bar
colorbar = plt.colorbar()
colorbar.set_label("Density", fontsize=12)

# adding additional visual elements
plt.xticks(fontsize=10)
plt.yticks(fontsize=12)
plt.tight_layout()

# saving the plot as a png
plt.savefig("scatter_plot.png", dpi=300)