#!/usr/bin/env python3

""" A classic boring car ride tune - 99 bottles, but truncated """

def prompt():
    bottles = input("How many bottles are we starting with? ")

if type(bottles) == str:
    print("

