#!/usr/bin/env python3

""" A classic boring car ride tune - 99 bottles"""

bottles = int(input("How many bottles are we starting with? "))
drop_one = bottles - 1

# using while bottles is more than 1
while int(bottles) > 1:
    print(f"{bottles:n} bottles of beer on the wall, {bottles:n} bottles of beer. Take one down, pass it around, {drop_one:n} + bottles of beer on the wall.")
    bottles -= 1
    drop_one -= 1

# final bottle (bottle = 1)
print(f"{bottles:n} bottle of beer on the wall, {bottles:n} bottle of beer. Take one down, it's the last one now, no more bottles of beer on the wall.")

# finally home
print("Hooray! You've made it through the drive!")
