#!/usr/bin/env python3

# defining all the variables to play with
challenge = ["science", "turbo", ["goggles", "eyes"], "nothing"]
trial = ["science", "turbo", {"eyes": "goggles", "goggles": "eyes"}, "nothing"]
nightmare = [{"slappy": "a", "text": "b", "kumquat": "goggles", "user":{"awesome": "c", "name": {"first": "eyes", "last": "toes"}},"banana": 15, "d": "nothing"}]

eyes = nightmare[0]["user"]["name"]["first"]
goggles = nightmare[0].get("kumquat")
nothing = nightmare[0].get("d")

print(f"My {eyes}! The {goggles} do {nothing}!")
